[2024-11-19T03:12:34.334+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_data.generate_fraud_data manual__2024-11-19T03:12:32.390468+00:00 [queued]>
[2024-11-19T03:12:34.343+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_data.generate_fraud_data manual__2024-11-19T03:12:32.390468+00:00 [queued]>
[2024-11-19T03:12:34.344+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-19T03:12:34.358+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): generate_fraud_data> on 2024-11-19 03:12:32.390468+00:00
[2024-11-19T03:12:34.370+0000] {standard_task_runner.py:60} INFO - Started process 689 to run task
[2024-11-19T03:12:34.372+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'generate_data', 'generate_fraud_data', 'manual__2024-11-19T03:12:32.390468+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmpsb0yjinn']
[2024-11-19T03:12:34.374+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask generate_fraud_data
[2024-11-19T03:12:34.413+0000] {task_command.py:423} INFO - Running <TaskInstance: generate_data.generate_fraud_data manual__2024-11-19T03:12:32.390468+00:00 [running]> on host 140f6b81ae00
[2024-11-19T03:12:34.484+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='generate_data' AIRFLOW_CTX_TASK_ID='generate_fraud_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T03:12:32.390468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T03:12:32.390468+00:00'
[2024-11-19T03:12:34.542+0000] {logging_mixin.py:188} INFO - Error inserting labeled transaction data: 1062 (23000): Duplicate entry '392' for key 'labeled_transactions.PRIMARY'
[2024-11-19T03:12:34.543+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-11-19T03:12:34.552+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=generate_data, task_id=generate_fraud_data, execution_date=20241119T031232, start_date=20241119T031234, end_date=20241119T031234
[2024-11-19T03:12:34.586+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-19T03:12:34.600+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
