[2024-11-18T03:27:55.569+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_data.generate_transaction_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T03:27:55.585+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_data.generate_transaction_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T03:27:55.586+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-18T03:27:55.604+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): generate_transaction_data> on 2024-11-17 00:00:00+00:00
[2024-11-18T03:27:55.615+0000] {standard_task_runner.py:60} INFO - Started process 1802 to run task
[2024-11-18T03:27:55.618+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'generate_data', 'generate_transaction_data', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmpu3sk4x0v']
[2024-11-18T03:27:55.620+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask generate_transaction_data
[2024-11-18T03:27:55.680+0000] {task_command.py:423} INFO - Running <TaskInstance: generate_data.generate_transaction_data scheduled__2024-11-17T00:00:00+00:00 [running]> on host 140f6b81ae00
[2024-11-18T03:27:55.811+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='generate_data' AIRFLOW_CTX_TASK_ID='generate_transaction_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T03:27:55.832+0000] {logging_mixin.py:188} INFO - Error creating table: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customer_transactions_transaction_id_seq, 2200) already exists.
[2024-11-18T03:27:56.096+0000] {logging_mixin.py:188} INFO - Data generation complete.
[2024-11-18T03:27:56.098+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-11-18T03:27:56.113+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=generate_data, task_id=generate_transaction_data, execution_date=20241117T000000, start_date=20241118T032755, end_date=20241118T032756
[2024-11-18T03:27:56.152+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T03:27:56.176+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
